---
- hosts: all
  remote_user: vagrant
  vars:
    nginx_src_rpm: nginx-1.9.10-1.el7.ngx.src.rpm
    openssl_src: openssl-1.0.2f
    pkg_release: 2.el7.sse2
    libsass_ver: 3.3.3
  tasks:
  - name: Install EPEL Yum repo
    yum: name=epel-release state=present
    become: yes
    become_user: root
  - name: Install build tools from CentOS repos
    yum: name={{ item }} state=present
    become: yes
    become_user: root
    with_items:
    - ca-certificates
    - curl
    - libcurl
    - git
    - glib2
    - rsync
    - make
    - patch
    - bzip2
    - xz
    - tar
    - autoconf
    - automake
    - libtool
    - zlib-devel
    - glibc-devel
    - libaio-devel
    - pcre-devel
    - nss-devel
    - nss-softokn-devel
    - nss-softokn-freebl-devel
    - nspr-devel
    - libgcrypt-devel
    - libgpg-error-devel
    - libatomic_ops-devel
    - rpm-build
    - redhat-rpm-config
    - mock
    - scl-utils
    - centos-release-scl-rh
  - name: Install build tools from Devtoolset-3 repo
    yum: name={{ item }} state=present
    become: yes
    become_user: root
    with_items:
    - devtoolset-3-binutils
    - devtoolset-3-gcc
    - devtoolset-3-gcc-c++
  - name: Delete recursively old rpmbuild directory
    file: dest=rpmbuild state=absent
  - name: Create new rpmbuild directory
    file: dest=rpmbuild/BUILD state=directory recurse=yes
  - name: Download Nginx RPM source package
    get_url: url=http://nginx.org/packages/mainline/centos/7/SRPMS/{{ nginx_src_rpm }} dest=~/rpmbuild/nginx-src.rpm
  - name: Extract Nginx RPM source package
    shell: rpm -i ~/rpmbuild/nginx-src.rpm
  - name: Create pcre directory
    file: dest=rpmbuild/BUILD/pcre state=directory
  - name: Download latest PCRE
    shell: curl -s -S -L 'http://sourceforge.net/projects/pcre/files/latest/download?source=navbar' | tar -C rpmbuild/BUILD/pcre --strip-components=1 -xj
  - name: Create openssl directory
    file: dest=rpmbuild/BUILD/openssl state=directory
  - name: Download OpenSSL
    shell: curl -s -S -L http://www.openssl.org/source/{{ openssl_src }}.tar.gz | tar -C rpmbuild/BUILD/openssl --strip-components=1 -xz
  - name: Download CloudFlare CHACHA20-POLY1305 patch
    get_url: url=https://raw.githubusercontent.com/cloudflare/sslconfig/master/patches/openssl__chacha20_poly1305_cf.patch dest=~/rpmbuild/openssl__chacha20_poly1305_cf.patch
  - name: Apply CHACHA20-POLY1305 patch to OpenSSL
    shell: patch -p1 < ~/rpmbuild/openssl__chacha20_poly1305_cf.patch
    args:
      chdir: ~/rpmbuild/BUILD/openssl
  - name: Run OpenSSL configure script to apply CHACHA20-POLY1305
    shell: source /opt/rh/devtoolset-3/enable && ./config
    args:
      chdir: ~/rpmbuild/BUILD/openssl
  - name: Create libsass directory
    file: dest=rpmbuild/BUILD/libsass state=directory
  - name: Download libsass
    shell: curl -s -S -L 'https://codeload.github.com/sass/libsass/tar.gz/{{ libsass_ver }}' | tar -C rpmbuild/BUILD/libsass --strip-components=1 -xz
  - name: Clone sass-nginx-module from Github
    git: repo=https://github.com/mneudert/sass-nginx-module.git dest=rpmbuild/BUILD/sass-nginx-module
  - name: 'Modify RPM spec: remove openssl package dependencies'
    shell: "sed -i '/Requires: \\(lib\\)\\?openssl/d' rpmbuild/SPECS/nginx.spec"
  - name: 'Modify RPM spec: remove pcre package dependencies'
    shell: "sed -i '/Requires: pcre/d' rpmbuild/SPECS/nginx.spec"
  - name: 'Modify RPM spec: build with static PCRE library'
    shell: "sed -i '/--with-ipv6/a \\ \\ \\ \\ \\ \\ \\ \\ --with-pcre=../pcre \\\\ ' rpmbuild/SPECS/nginx.spec"
  - name: 'Modify RPM spec: enable PCRE JIT'
    shell: "sed -i '/--with-pcre/a \\ \\ \\ \\ \\ \\ \\ \\ --with-pcre-jit \\\\ ' rpmbuild/SPECS/nginx.spec"
  - name: 'Modify RPM spec: build with static OpenSSL library'
    shell: "sed -i '/--with-ipv6/a \\ \\ \\ \\ \\ \\ \\ \\ --with-openssl=../openssl \\\\ ' rpmbuild/SPECS/nginx.spec"
  - name: 'Modify RPM spec: build OpenSSL without insecure crypto'
    shell: "sed -i '/--with-openssl=/a \\ \\ \\ \\ \\ \\ \\ \\ --with-openssl-opt=\"no-krb5 no-ssl2 no-ssl3 no-comp no-dtls no-rc4\" \\\\ ' rpmbuild/SPECS/nginx.spec"
  - name: 'Modify RPM spec: build with dynamic libatomic_ops'
    shell: "sed -i '/--with-ipv6/a \\ \\ \\ \\ \\ \\ \\ \\ --with-libatomic \\\\ ' rpmbuild/SPECS/nginx.spec"
  - name: 'Modify RPM spec: add build identifier'
    shell: "sed -i \"/--group=/a \\ \\ \\ \\ \\ \\ \\ \\ --build='SSE2, {{ openssl_src }} + ChaCha20-Poly1305, PCRE JIT, libatomic_ops, TCP Fast Open, SELinux + modules: Sass, PageSpeed' \\\\\\ \" rpmbuild/SPECS/nginx.spec"
  - name: 'Modify RPM spec: add module sass-nginx-module'
    shell: "sed -i '/--with-pcre-jit/a \\ \\ \\ \\ \\ \\ \\ \\ --add-module=../sass-nginx-module \\\\ ' rpmbuild/SPECS/nginx.spec"
  - name: 'Modify RPM spec: CC options'
    shell: "sed -i 's/pcre-config --cflags./\\0 -mmmx -msse -msse2 -DTCP_FASTOPEN=23/' rpmbuild/SPECS/nginx.spec"
  - name: 'Modify RPM spec: remove trailing whitespace from configure lines'
    shell: sed -i "s/ $//" rpmbuild/SPECS/nginx.spec
  - name: 'Modify RPM spec: update release'
    shell: 'sed -i "s/Release: .*\.ngx/Release: {{ pkg_release }}/" rpmbuild/SPECS/nginx.spec'
  - name: 'Modify sass-nginx-module config for a static build'
    shell: "sed -i 's/^\\(CORE_LIBS=.*\\) -lsass/\\1/' rpmbuild/BUILD/sass-nginx-module/config"
  - name: 'Modify sass-nginx-module config linker options'
    shell: "sed -i '/^CORE_LIBS=/a NGX_LD_OPT=\"$NGX_LD_OPT ../libsass/src/.libs/libsass.a\" ' rpmbuild/BUILD/sass-nginx-module/config"
  - name: 'Modify sass-nginx-module config includes'
    shell: "sed -i '/^CORE_LIBS=/a CORE_INCS=\"$CORE_INCS ../libsass/include\" ' rpmbuild/BUILD/sass-nginx-module/config"
  - name: 'Autoreconf libsass'
    shell: source /opt/rh/devtoolset-3/enable && autoreconf --force --install
    args:
      chdir: ~/rpmbuild/BUILD/libsass
  - name: 'Configure libsass for static build'
    shell: source /opt/rh/devtoolset-3/enable && ./configure --disable-shared --enable-static
    args:
      chdir: ~/rpmbuild/BUILD/libsass
  - name: 'Build libsass'
    shell: source /opt/rh/devtoolset-3/enable && make
    args:
      chdir: ~/rpmbuild/BUILD/libsass
  - name: Build RPM packages
    shell: source /opt/rh/devtoolset-3/enable && rpmbuild -ba rpmbuild/SPECS/nginx.spec

