---
- hosts: all
  remote_user: vagrant
  vars_files:
  - variables.yml
  vars:
    nginx_src_rpm: "nginx-{{ nginx_ver }}.el7.ngx.src.rpm"
    pkg_release: "{{ release_ver }}.el7.sse2"
  tasks:
  - name: Delete recursively old rpmbuild directory
    file: dest=rpmbuild state=absent
  - name: Create new rpmbuild directory
    file: dest=rpmbuild/BUILD state=directory recurse=yes
  - name: Download Nginx RPM source package
    get_url: url=http://nginx.org/packages/mainline/centos/7/SRPMS/{{ nginx_src_rpm }} dest=~/rpmbuild/nginx-src.rpm
  - name: Extract Nginx RPM source package
    shell: rpm -i ~/rpmbuild/nginx-src.rpm
  - name: 'Modify RPM spec: remove openssl package dependencies'
    shell: "sed -i '/Requires: \\(lib\\)\\?openssl/d' rpmbuild/SPECS/nginx.spec"
  - name: 'Modify RPM spec: remove pcre package dependencies'
    shell: "sed -i '/Requires: pcre/d' rpmbuild/SPECS/nginx.spec"
  - name: 'Modify RPM spec: build with static PCRE library'
    shell: "sed -i '/--with-ipv6/a \\ \\ \\ \\ \\ \\ \\ \\ --with-pcre=../pcre \\\\ ' rpmbuild/SPECS/nginx.spec"
  - name: 'Modify RPM spec: enable PCRE JIT'
    shell: "sed -i '/--with-pcre/a \\ \\ \\ \\ \\ \\ \\ \\ --with-pcre-jit \\\\ ' rpmbuild/SPECS/nginx.spec"
  - name: 'Modify RPM spec: build with static OpenSSL library'
    shell: "sed -i '/--with-ipv6/a \\ \\ \\ \\ \\ \\ \\ \\ --with-openssl=../openssl \\\\ ' rpmbuild/SPECS/nginx.spec"
  - name: 'Modify RPM spec: add variable for OpenSSL configuration options'
    lineinfile: dest=rpmbuild/SPECS/nginx.spec insertbefore='%define COMMON_CONFIGURE_ARGS' line='%define openssl_config_options no-krb5 no-ssl2 no-ssl3 no-comp no-dtls no-rc4'
  - name: 'Modify RPM spec: build OpenSSL without insecure crypto'
    lineinfile: state=present insertbefore='--with-cc-opt=' line='    --with-openssl-opt="%{openssl_config_options}" \ ' dest=rpmbuild/SPECS/nginx.spec
  - name: 'Modify RPM spec: build OpenSSL without insecure crypto in debug build'
    lineinfile: state=present insertbefore='--with-debug' line='    --with-openssl-opt="%{openssl_config_options}" \  ' dest=rpmbuild/SPECS/nginx.spec
  - name: 'Modify RPM spec: build with dynamic libatomic_ops'
    shell: "sed -i '/--with-ipv6/a \\ \\ \\ \\ \\ \\ \\ \\ --with-libatomic \\\\ ' rpmbuild/SPECS/nginx.spec"
  - name: 'Modify RPM spec: add variable for Nginx build identified'
    lineinfile: "dest=rpmbuild/SPECS/nginx.spec insertbefore='%define COMMON_CONFIGURE_ARGS' line='%define cust_build_id github.com/istenrot/centos-nginx-http2: {{ openssl_src }} + ChaCha20-Poly1305, PCRE JIT, PageSpeed'"
  - name: 'Modify RPM spec: add build identifier'
    lineinfile: state=present insertbefore='--with-cc-opt=' line='    --build="%{cust_build_id}" \ ' dest=rpmbuild/SPECS/nginx.spec
  - name: 'Modify RPM spec: add build identifier in debug build'
    lineinfile: state=present insertbefore='--with-debug' line='    --build="%{cust_build_id}" \  ' dest=rpmbuild/SPECS/nginx.spec
  - name: 'Modify RPM spec: add dynamic module ngx_pagespeed'
    shell: "sed -i '/--with-pcre-jit/a \\ \\ \\ \\ \\ \\ \\ \\ --add-dynamic-module=../ngx_pagespeed \\\\ ' rpmbuild/SPECS/nginx.spec"
  - name: 'Modify RPM spec: CC options'
    shell: "sed -i 's/pcre-config --cflags./\\0 -mmmx -msse -msse2 -DTCP_FASTOPEN=23/' rpmbuild/SPECS/nginx.spec"
  - name: 'Modify RPM spec: remove trailing whitespace from configure lines'
    shell: sed -i "s/ $//" rpmbuild/SPECS/nginx.spec
  - name: 'Modify RPM spec: update release'
    shell: 'sed -i "s/Release: .*\.ngx/Release: {{ pkg_release }}/" rpmbuild/SPECS/nginx.spec'

